### ISSUE TITLE
New names for the QCArchive Ecosystem vs the MolSSI QCFractal instance

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCArchiveWebsite#32]
When showing QCArchive to potential new users and collaborators, we do not make a strong distinction between the software ecosystem and the central MolSSI instance. This can lead to confusion. For example, some get the impression that all data generated by a QCFractal instance will automatically be uploaded to the MolSSI Database, or that running QCFractal will cause your compute resources to be donated to the service of MolSSI's task queue.

I propose that we make a clear distinction between the MolSSI QCFractal instance and the QCArchive ecosystem in the following ways:

1. We choose new names to replace terms like "MolSSI QCFractal instance" and "QCArchive ecosystem"
2. We brand these two objects differently, e.g. with different logos or color schemes. 
3. We update the website to reflect this distinction.

There has been some previous discussion about this on Slack. This issue seeks to centralize that discussion, and some of the Slack discussion will be reproduced below.

**Comment by mattwelborn** [comment]
Regarding item 1, the MolSSI QCFractal instance could be called the "QCArchive". To my knowledge, this is what people think of when they hear the name "QCArchive". Further, the primary role of the MolSSI QCFractal instance is to serve as an archive for quantum chemical data, whereas the role of the "QCArchive Ecosystem" additionally includes compute/workflow management (QCFractal and QCEngine) and data access (QCPortal).

**Comment by mattwelborn** [comment]
Lori Burns made the following suggestion for names, and a FAQ about the MolSSI instance:

```
TMQCAI := The MolSSI QCA Instance


               QCA
---------------------------------

TMQCAI    QCAeco    Your QCA Instance
------    ------    -----------------

What is it?
* a single database with millions of CMS records run by MolSSI or donated to MolSSI
* several open-source software repositories with coherent focus that together power/enable a QCA database instance and separately help other CMS software projects.
* a single database you spin up locally and own. start one per lab group or per project, or per day.

Where does it live?
* on a machine at MolSSI headquarters.
* on GitHub, with clones on hundreds of user and developer systems.
* whereever you choose -- cluster, laptop, Faraday cage -- depending on the level of collaborator access, longevity, and security needed.

How long does it last? How long will it be in working order? What if MolSSI folds?
* "permanent", as it's backed up by .... Robust, as its dependencies are Python, Postgres. Resiliant, as it's binary dictionaries in a pinch. When The MolSSI sunsets, TMQCAI will need a new home and maintainer, but since it's composed of binary dictionaries, in a pinch, records can be easily migrated.
* "permanent", as text files duplicated on hundreds of computers are hard to kill. The building blocks of Python, NumPy, Pandas, tend to have a broader support base than the whole of CMS
* you choose, from permanent (so long as your hardware and backup system lasts) to evanescent (the background-only, create-and-close QCFractalSnowflake). After a project is completed and published, it's encouraged to contribute records from your QCA Instance to TMQCAI.

Who can see it? Who can use it?
* anyone, by `command here`
* anyone, browse at GH:MolSSI/repos. License is BSD 3-Clause so academia, industry, personal use all welcome.
* those to whom you give access
```

and commented:

> I think something like the above (plus more questions) can help. It’s true that these are the boundaries of the project that I know b/c I’ve been around it and that don’t get prominent documentation, as opposed to the nuts-and-bolts of operation. Yes, TMQACI is a mouthful, but it’s also unique and hence easily recognized and associated with.

**Comment by dgasmith** [comment]
Several potential names:
 - SCABB - Scalable Chemistry and Building Blocks (not great connotations)
 - QSCALE - Quantum Scalable and ...?
 - COMOROS - Chemistry cOMpOsable aRchival ecOsystem at Scale

Generator [here](https://acronymify.com/search?q=chemistry+composable+archival+ecosystem+scale).

I do lean a bit towards "QCArchive" being the MolSSI instance and renaming the ecosystem. As @mattwelborn mentioned, "Archive" has definitive connotations and lacks the workflow/distribution/archival/composable blocks.

**Comment by mattwelborn** [comment]
Some riffs:

* SCREAD: Scalable Chemistry wRapper, Executor, And Database
* SCREAM: Scalable Chemistry Repository, Ecosystem, And Manager
* SCARABB: Scalable Chemistry Archive, Runner, and Building Blocks

**Comment by loriab** [comment]
dangerous website:

* CHIROPRACTOR: CHemIstRy cOmPosable aRchivAl eCosysTem sOftwaRe
* COBALT: Chemistry cOmposaBle ArchivaL sofTware
* HYPOCAUST: cHemistrY comPOsable sCAle qUantum SofTware

**Comment by Lnaden** [comment]
QC FREEPORT: FRactal Engine Elemental PORTal?

**Comment by mattwelborn** [comment]
We could call the whole ecosystem "QCFractal" and the rename QCFractal to something like "QCPipeline".

**Comment by Lnaden** [comment]
I personally would like to avoid renaming any of the individual packages.

**Comment by loriab** [comment]
QCKraken for the ecosys, for it is encompassing and has its tentacles in many directions. Then QCA for TMQCAI and QCK for QCASS.

**Comment by mattwelborn** [comment]
It's more of a QCPortugueseManOfWar... (I like QCKraken. QCthulu? )

**Comment by dgasmith** [comment]
QCVolair, EosQuantum, ...

SQ*, - Scalable Quantum*
SC*Q*, - Scalable and Composable ... Quantum*

**Comment by doaa-altarawy** [comment]
I'm also with keeping QCArchive for the MolSSI database instance as it indicates an "archive" of data. 

My thoughts:

- For the ecosystem, I suggest having a name that reflects QC+compute+store+automation. It's not a workflow like Parsal, not just a database like NOMAD, and not for any scientific domain, it QC data for all molecular sciences usage.
- I think the name should be simple and doesn't need us to tell ppl how to pronounce it.
- The name shouldn't be in the dictionary and doesn't point to something else famous:)
- I'm more with tweaked meaningful words rather than acronyms. 
- We can use "toolkit" too to indicate that the "ecosystem" is connected.


I think inspiring nice examples: QCArchive:) Dash, plotly, Docker, Tensorflow, SmartSheets, ProcessMaker, WordPress, Canvas, Composer, DataGrip, BioConductor, BioTracker, JMol, 

Not good in my opinion:
Bio-G (doing what?), LI-COR, VLC (media player), BALL (dictionary), GLib (going what?), YARP, EOS.IO (how do u pronounce it?), Odoo, KNIME, 

Check here [https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_packages](url) 
you will see which one looks attractive over others.

So for our ecosystem, things like: QCAutoFlow, QC-Composer,

**Comment by doaa-altarawy** [comment]
> I personally would like to avoid renaming any of the individual packages.

I agree, but QCFractal might need to receive the name of the ecosystem to make ppl less confused.

**Comment by mattwelborn** [comment]
Thanks for the insightful comment @doaa-altarawy. I agree that we should think more about "tweaked meaningful words"-type names.

**Comment by dgasmith** [comment]
The QCFractal ecosystem? Lots of downsides here, but simple.

+1 for the inspiring names from @doaa-altarawy.

**Comment by mattwelborn** [comment]
Current plan "QCArchive" and the "QCFractal Software Ecosystem". This will be decided by Friday.

**Comment by twindus** [comment]
I am concerned that QCArchive has already been "branded" and most people that I talk to think of it as the software and not the instance at MolSSI.  

I don't think QCFractal is descriptive enough to tell people what it is (keeping in mind @doaa-altarawy 's comments).  It really doesn't tell you what it does.  "Ecosystem" seems like a reasonable thing to add on since there is a lot to the software platform.

My $0.02.

**Comment by dgasmith** [comment]
@twindus Thanks for the comments! It is interesting as most of the community that we talk to seems to think "QCArchive" as the MolSSI instance, do you think it will be too much to shift their perspectives?

I think there are certainly better names than "QCFractal", but we have not been able to come up with them. We have been racking our brains out here for the past few days without too much progress.

**Comment by twindus** [comment]
@dgasmith I honestly don't know if I can answer your question without pinging some folks.  I do know that the NSF and a good number of the reviewers from our review thought of it as the software.

For the QCFractal: If you had to sum up the software in one sentence, what would that be?  (And not a run-on sentence...  :) )  In other words, what is the most important thing that you want users to know the software can do?

**Comment by lothian** [comment]
I'm going to chime in here, too, to reiterate some comments I made to DS on Monday (I think).  I think it would be a significant mistake to alter the branding of QCArchive at this point.  I have spoken to many people about the QCArchive, and I've never had any feedback that suggests confusion on this point.  Are you absolutely positive that the misunderstanding is sufficiently widespread to warrant such a change, or are you unintentionally magnifying a few examples to make the issue seem more serious that it is?

**Comment by mattwelborn** [comment]
@twindus @lothian I think it's might be helpful summarize some of the discussions that we've had internally and clarify the steps that will intend to take. 

The name of the project will remain QCArchive and the website will remain qcarchive.molssi.org. We feel that QCArchive is a strong name, that people know it, and that there is value in maintaining continuity. That said, the current website conflates the two components of the project, and we feel that confusion would be reduced by calling the MolSSI instance by a different name than the software ecosystem. 

The plan is to keep the current content of the website just as it is, except that:
* the phrase "QCArchive Ecosystem" will become "QCFractal Ecosystem" 
* the four items on the "Get Started" page will be split into two categories depending on whether they apply to the MolSSI database or to the software stack. 
* in the future, the content on the website may be edited or reorganized to sharpen the use cases for the MolSSI database versus the software stack.

We don't want to rush this, but we feel it's important that we make these changes before the stable beta release. Our intention is to not do any renaming in the future, if it can be avoided.

**Comment by loriab** [comment]
* If the community is equally unclear in all directions (QCA = database, software, both), I tend to return to the `[QCArchive: database or software](FAQ)` solution, since this is a confusion that can be cleared up once and quickly.

* For one more crack at a software ecosystem name, I'll suggest **QCLattice** as being connotative of the connection role of the QCA repos and distinctive enough for a proper noun. While I agree with Doaa in not going too far from a project's utility, I'd rather names be distinctive and linkable after ppl know the topic. (Case in point, all the uninitiated think I'm saying science "sci" for psi4.)

* My go on a 1-sentence description: QCFractal Ecosystem are several co-developed software projects that support uniform data generation, access, scheduling, querying, and storage for CMS community codes.

**Comment by twindus** [comment]
@mattwelborn Thanks for trying to clarify the current conversation.  I would be much more supportive of the solution that @loriab suggested since it keeps the QCArchive name to both the software and the database.  Then you could specifically refer to the QCArchive software (or ecosystem if you like that) and the QCArchive database. 

I also agree that this should be settled before the beta release when it will be much harder to make any changes.

I am not a big fan of QCLattice for the same reason that QCFractal - they don't convey what it does.  Based on @loriab 's description maybe something like QCDataStore?  (Although I still think just clarifying QCArchive is the best solution.)  It doesn't emphasize the generation, but it could be store as in storage and store as in getting form (although it has the purchase aspect - although most online software stores have free stuff too).

**Comment by dgasmith** [comment]
@twindus Your phrasing about "QCDataStore" hits upon one of our fears about the name "QCArchive". There are plenty of researchers using Fractal as a workflow tool, packages consuming Engine IO to become agnostic about program backend, and Elemental for conversion factors and parsing technology. We use the QCFractal stack to archive data, but it is not the only use case nor the one the greater community will focus on.

We have tried out QCArchive database/QCArchive software in several communities and there seemed to be quite a bit of confusion with this terminology that they are one and the same. I feel like we have cast a reasonably wide net (~35 researchers), but that might not have the correct distribution of people.

**Comment by loriab** [comment]
For the ecosys, I thought we want to emphasize everything _but_ the data, as the data is QCArchive. The greater QCA project minus the data leaves software/connectivity/support to my impression.

fwiw, I surveyed some Sherrill Group ppl with "QCArchive is database, software, both, or neither?" and got one both and two 80% software.

**Comment by twindus** [comment]
@dgasmith Totally understand that QCDataStore might not be the right thing, just thought I would brainstorm a bit.

**Comment by twindus** [comment]
I am kind of surprised that people would be confused about the difference between a database and the software.  If that is the case, then probably any wording is going to cause confusion.  Perhaps some other name for the actual database at MolSSI would be appropriate to make it concrete - something like "MolSSI QM Database".  It is kind of long, but would be pretty specific (I don't know how you clarify database any further).

**Comment by lothian** [comment]
I strongly support @loriab's suggestion of a FAQ to differentiate between the two without otherwise changing the naming convention.

**Comment by dgasmith** [comment]
@lothian Ok, we will do what we can within those constraints. We may have to add this to an area outside of the FAQ as the FAQ currently is only hit by ~1% of users via Google Analytics if that will still work for you.

**Comment by dgasmith** [comment]
Ok, I believe we have overhauled the website to get this primary point across. Please open new issues as they arise surrounding this topic.
